/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    CardLeft: typeof import('./src/components/card-left.vue')['default']
    CardLeftTag: typeof import('./src/components/card-leftTag.vue')['default']
    CardLife: typeof import('./src/components/card-life.vue')['default']
    CardVideo: typeof import('./src/components/card-video.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    copy: typeof import('./src/components/container copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleto: typeof import('element-plus/es')['ElSkeleto']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSpan: typeof import('element-plus/es')['ElSpan']
    ElSpance: typeof import('element-plus/es')['ElSpance']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Moyuimage: typeof import('./src/components/moyuimage.vue')['default']
    Moyuvideo: typeof import('./src/components/moyuvideo.vue')['default']
    TimeRubric: typeof import('./src/components/time-rubric.vue')['default']
    UseDark: typeof import('./src/components/useDark.vue')['default']
  }
}
