/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    CardVideo: typeof import('./src/components/card-video.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    'Container copy': typeof import('./src/components/container copy.vue')['default']
    copy: typeof import('./src/components/container copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Moyuimage: typeof import('./src/components/moyuimage.vue')['default']
    Moyuvideo: typeof import('./src/components/moyuvideo.vue')['default']
    TimeRubric: typeof import('./src/components/time-rubric.vue')['default']
    UseDark: typeof import('./src/components/useDark.vue')['default']
  }
}
